from ClassHandlers.camera_handler import CameraHandler
from DefaultClassModels.Configs.default_camera_config_physical import default_camera_config_physical
from DefaultClassModels.Configs.default_camera_config_stream import default_camera_config_stream

camera_handler_from_physical = CameraHandler(config=default_camera_config_physical)
camera_handler_from_stream = CameraHandler(config=default_camera_config_stream)

